export const HELP_TEXT = [
  '🤖 **ClaudeTalk 指令帮助**',
  '',
  '**会话管理**',
  '  /new            清空本地会话记忆，开启全新对话',
  '  /session        查看当前会话详情',
  '  /session list   列出最近会话',
  '  /session name   为当前会话命名',
  '  /restart        重启机器人（仅私聊）',
  '  /help           显示本帮助信息',
  '',
  '**任务**',
  '  /tasks          查看手机待办列表',
  '  加入手机待办    将最近对话加入待办（卡片确认）',
  '',
  '**后台任务**',
  '  /task run <描述>    启动后台任务',
  '  /task status        查看后台任务列表',
  '  /task cancel <id>   取消运行中的任务',
  '',
  '**远程访问**',
  '  开启远程    启动 Cloudflare Tunnel + Dashboard',
  '  关闭远程    停止 Cloudflare Tunnel + Dashboard',
  '  访问地址: term.linximengji.com',
  '',
  '**系统管理**',
  '  /log              查看最近运行日志',
  '  /daemon restart   重启 ops-daemon',
  '',
  '发送其他任意消息将由 Claude Code 处理。',
].join('\n')

/** 上线通知精简版 — 只显示核心指令，引导用户发 /help 看全部 */
export function buildOnlineNotification(workDir: string): string {
  return [
    '✅ ClaudeTalk 已上线',
    `📁 工作目录: ${workDir}`,
    '',
    '💡 常用指令：',
    '  /new      新会话',
    '  /restart  重启机器人',
    '  /status   服务状态',
    '  /help     显示全部指令',
    '',
    '🌐 远程终端',
    '  开启远程  启动 Dashboard',
    '  关闭远程  停止 Dashboard',
    '',
    '  访问地址: term.linximengji.com',
  ].join('\n')
}
